# Generated by Django 5.2 on 2025-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sport', models.CharField(max_length=50)),
                ('achievements', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='athletes/')),
            ],
        ),
    ]
